#!/bin/bash

apt update
apt install git unzip wget -y
wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
mv composer.phar /usr/local/bin/composer
cd /var/www/html
composer install
chown -R 1000:1000 composer.lock vendor
docker-php-entrypoint
php -a
